#!/bin/sh
#
# Reformats any staged python files with `black`, and prompts to review
# changes.

format () {
	for f in "$@"
	do
		shift
		case "$f" in
		*.py)
			test -e "$f" && set -- "$@" "$f"
		esac
	done

	if test $# -eq 0
	then
		# No python files being committed, so do nothing.
		exit 0
	fi

	if ! black --check "$@" >/dev/null 2>&1
	then
		diff=$(black --diff --color --quiet "$@")
		black "$@"
		printf '\n%s\n\n\033[1m%s\033[m\n' \
			"$diff" \
			'Please review changes and re-stage'
		exit 1
	fi
}

staged_files=$(git diff --staged --name-only)

format $staged_files
